// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpfoperatorconfigs.operator.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "operator.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPFOperatorConfig",
    plural = "dpfoperatorconfigs"
)]
#[kube(namespaced)]
#[kube(status = "DpfOperatorConfigStatus")]
#[kube(schema = "disabled")]
pub struct DpfOperatorConfigSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "cniInstaller"
    )]
    pub cni_installer: Option<DpfOperatorConfigCniInstaller>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuDetector"
    )]
    pub dpu_detector: Option<DpfOperatorConfigDpuDetector>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuServiceController"
    )]
    pub dpu_service_controller: Option<DpfOperatorConfigDpuServiceController>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flannel: Option<DpfOperatorConfigFlannel>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "imagePullSecrets"
    )]
    pub image_pull_secrets: Option<Vec<String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "kamajiClusterManager"
    )]
    pub kamaji_cluster_manager: Option<DpfOperatorConfigKamajiClusterManager>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multus: Option<DpfOperatorConfigMultus>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub networking: Option<DpfOperatorConfigNetworking>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nvipam: Option<DpfOperatorConfigNvipam>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub overrides: Option<DpfOperatorConfigOverrides>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "ovsCNI")]
    pub ovs_cni: Option<DpfOperatorConfigOvsCni>,
    #[serde(rename = "provisioningController")]
    pub provisioning_controller: DpfOperatorConfigProvisioningController,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceSetController"
    )]
    pub service_set_controller: Option<DpfOperatorConfigServiceSetController>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "sfcController"
    )]
    pub sfc_controller: Option<DpfOperatorConfigSfcController>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "sriovDevicePlugin"
    )]
    pub sriov_device_plugin: Option<DpfOperatorConfigSriovDevicePlugin>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "staticClusterManager"
    )]
    pub static_cluster_manager: Option<DpfOperatorConfigStaticClusterManager>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigCniInstaller {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deployInTargetCluster"
    )]
    pub deploy_in_target_cluster: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "helmChart")]
    pub helm_chart: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub installer: Option<DpfOperatorConfigCniInstallerInstaller>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigCniInstallerInstaller {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigCniInstallerInstallerResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigCniInstallerInstallerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigCniInstallerInstallerResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigCniInstallerInstallerResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigCniInstallerInstallerResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigCniInstallerInstallerResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigDpuDetector {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub daemon: Option<DpfOperatorConfigDpuDetectorDaemon>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigDpuDetectorDaemon {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigDpuDetectorDaemonResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigDpuDetectorDaemonResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigDpuDetectorDaemonResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigDpuDetectorDaemonResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigDpuDetectorDaemonResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigDpuDetectorDaemonResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigDpuServiceController {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub controller: Option<DpfOperatorConfigDpuServiceControllerController>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "disableDPUReadyTaints"
    )]
    pub disable_dpu_ready_taints: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigDpuServiceControllerController {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigDpuServiceControllerControllerResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigDpuServiceControllerControllerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigDpuServiceControllerControllerResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigDpuServiceControllerControllerResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigDpuServiceControllerControllerResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigDpuServiceControllerControllerResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigFlannel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cni: Option<DpfOperatorConfigFlannelCni>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub daemon: Option<DpfOperatorConfigFlannelDaemon>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deployInTargetCluster"
    )]
    pub deploy_in_target_cluster: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "helmChart")]
    pub helm_chart: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<DpfOperatorConfigFlannelImage>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "podCIDR")]
    pub pod_cidr: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigFlannelCni {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigFlannelDaemon {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigFlannelDaemonResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigFlannelDaemonResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigFlannelDaemonResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigFlannelDaemonResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigFlannelDaemonResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigFlannelDaemonResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigFlannelImage {
    #[serde(rename = "flannelCNI")]
    pub flannel_cni: String,
    #[serde(rename = "kubeFlannel")]
    pub kube_flannel: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigKamajiClusterManager {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub controller: Option<DpfOperatorConfigKamajiClusterManagerController>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigKamajiClusterManagerController {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigKamajiClusterManagerControllerResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigKamajiClusterManagerControllerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigKamajiClusterManagerControllerResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigKamajiClusterManagerControllerResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigKamajiClusterManagerControllerResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigKamajiClusterManagerControllerResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigMultus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cni: Option<DpfOperatorConfigMultusCni>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deployInTargetCluster"
    )]
    pub deploy_in_target_cluster: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "helmChart")]
    pub helm_chart: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigMultusCni {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigMultusCniResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigMultusCniResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigMultusCniResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigMultusCniResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigMultusCniResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigMultusCniResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigNetworking {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "controlPlaneMTU"
    )]
    pub control_plane_mtu: Option<i64>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "highSpeedMTU"
    )]
    pub high_speed_mtu: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigNvipam {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub controller: Option<DpfOperatorConfigNvipamController>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deployInTargetCluster"
    )]
    pub deploy_in_target_cluster: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "helmChart")]
    pub helm_chart: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node: Option<DpfOperatorConfigNvipamNode>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigNvipamController {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigNvipamControllerResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigNvipamControllerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigNvipamControllerResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigNvipamControllerResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigNvipamControllerResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigNvipamControllerResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigNvipamNode {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigNvipamNodeResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigNvipamNodeResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigNvipamNodeResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigNvipamNodeResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigNvipamNodeResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigNvipamNodeResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigOverrides {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuCNIBinPath"
    )]
    pub dpu_cni_bin_path: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuCNIPath"
    )]
    pub dpu_cni_path: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuOpenvSwitchBinPath"
    )]
    pub dpu_openv_switch_bin_path: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuOpenvSwitchRunPath"
    )]
    pub dpu_openv_switch_run_path: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuOpenvSwitchSystemSharedLib64Path"
    )]
    pub dpu_openv_switch_system_shared_lib64_path: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuOpenvSwitchSystemSharedPath"
    )]
    pub dpu_openv_switch_system_shared_path: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "flannelSkipCNIConfigInstallation"
    )]
    pub flannel_skip_cni_config_installation: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "kubernetesAPIServerPort"
    )]
    pub kubernetes_api_server_port: Option<i64>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "kubernetesAPIServerVIP"
    )]
    pub kubernetes_api_server_vip: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paused: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigOvsCni {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cni: Option<DpfOperatorConfigOvsCniCni>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deployInTargetCluster"
    )]
    pub deploy_in_target_cluster: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "helmChart")]
    pub helm_chart: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigOvsCniCni {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigOvsCniCniResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigOvsCniCniResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigOvsCniCniResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigOvsCniCniResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigOvsCniCniResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigOvsCniCniResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningController {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "bfCFGTemplateConfigMap"
    )]
    pub bf_cfg_template_config_map: Option<String>,
    #[serde(rename = "bfbPVCName")]
    pub bfb_pvc_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub controller: Option<DpfOperatorConfigProvisioningControllerController>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "customCASecretName"
    )]
    pub custom_ca_secret_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dmsTimeout"
    )]
    pub dms_timeout: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "installInterface"
    )]
    pub install_interface: Option<DpfOperatorConfigProvisioningControllerInstallInterface>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "maxDPUParallelInstallations"
    )]
    pub max_dpu_parallel_installations: Option<i32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "maxUnavailableDPUNodes"
    )]
    pub max_unavailable_dpu_nodes: Option<i32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "multiDPUOperationsSyncWaitTime"
    )]
    pub multi_dpu_operations_sync_wait_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub registry: Option<DpfOperatorConfigProvisioningControllerRegistry>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningControllerController {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigProvisioningControllerControllerResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningControllerControllerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigProvisioningControllerControllerResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigProvisioningControllerControllerResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningControllerControllerResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningControllerControllerResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningControllerInstallInterface {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "installViaGNOI"
    )]
    pub install_via_gnoi:
        Option<DpfOperatorConfigProvisioningControllerInstallInterfaceInstallViaGnoi>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "installViaHostAgent"
    )]
    pub install_via_host_agent:
        Option<DpfOperatorConfigProvisioningControllerInstallInterfaceInstallViaHostAgent>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "installViaRedfish"
    )]
    pub install_via_redfish:
        Option<DpfOperatorConfigProvisioningControllerInstallInterfaceInstallViaRedfish>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningControllerInstallInterfaceInstallViaGnoi {}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningControllerInstallInterfaceInstallViaHostAgent {}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningControllerInstallInterfaceInstallViaRedfish {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "bfbRegistry"
    )]
    pub bfb_registry:
        Option<DpfOperatorConfigProvisioningControllerInstallInterfaceInstallViaRedfishBfbRegistry>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "bfbRegistryAddress"
    )]
    pub bfb_registry_address: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "skipDPUNodeDiscovery"
    )]
    pub skip_dpu_node_discovery: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningControllerInstallInterfaceInstallViaRedfishBfbRegistry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub port: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigProvisioningControllerRegistry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub port: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigServiceSetController {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub controller: Option<DpfOperatorConfigServiceSetControllerController>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deployInTargetCluster"
    )]
    pub deploy_in_target_cluster: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "helmChart")]
    pub helm_chart: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigServiceSetControllerController {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigServiceSetControllerControllerResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigServiceSetControllerControllerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigServiceSetControllerControllerResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigServiceSetControllerControllerResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigServiceSetControllerControllerResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigServiceSetControllerControllerResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigSfcController {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub controller: Option<DpfOperatorConfigSfcControllerController>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deployInTargetCluster"
    )]
    pub deploy_in_target_cluster: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "helmChart")]
    pub helm_chart: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "secureFlowDeletionTimeout"
    )]
    pub secure_flow_deletion_timeout: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigSfcControllerController {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigSfcControllerControllerResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigSfcControllerControllerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigSfcControllerControllerResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigSfcControllerControllerResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigSfcControllerControllerResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigSfcControllerControllerResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigSriovDevicePlugin {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deployInTargetCluster"
    )]
    pub deploy_in_target_cluster: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deviceplugin: Option<DpfOperatorConfigSriovDevicePluginDeviceplugin>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "helmChart")]
    pub helm_chart: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigSriovDevicePluginDeviceplugin {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigSriovDevicePluginDevicepluginResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigSriovDevicePluginDevicepluginResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigSriovDevicePluginDevicepluginResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigSriovDevicePluginDevicepluginResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigSriovDevicePluginDevicepluginResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigSriovDevicePluginDevicepluginResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigStaticClusterManager {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub controller: Option<DpfOperatorConfigStaticClusterManagerController>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigStaticClusterManagerController {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<DpfOperatorConfigStaticClusterManagerControllerResources>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigStaticClusterManagerControllerResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<DpfOperatorConfigStaticClusterManagerControllerResourcesLimits>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<DpfOperatorConfigStaticClusterManagerControllerResourcesRequests>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigStaticClusterManagerControllerResourcesLimits {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigStaticClusterManagerControllerResourcesRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<IntOrString>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpfOperatorConfigStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}
