// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpudiscoveries.provisioning.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "provisioning.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUDiscovery",
    plural = "dpudiscoveries"
)]
#[kube(namespaced)]
#[kube(status = "DpuDiscoveryStatus")]
#[kube(schema = "disabled")]
pub struct DpuDiscoverySpec {
    #[serde(rename = "ipRangeSpec")]
    pub ip_range_spec: DpuDiscoveryIpRangeSpec,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "scanInterval"
    )]
    pub scan_interval: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workers: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDiscoveryIpRangeSpec {
    #[serde(rename = "ipRange")]
    pub ip_range: DpuDiscoveryIpRangeSpecIpRange,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDiscoveryIpRangeSpecIpRange {
    #[serde(rename = "endIP")]
    pub end_ip: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    #[serde(rename = "startIP")]
    pub start_ip: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDiscoveryStatus {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "foundDPUs")]
    pub found_dp_us: Option<i64>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "lastScanTime"
    )]
    pub last_scan_time: Option<String>,
}
