// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuservices.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUService",
    plural = "dpuservices"
)]
#[kube(namespaced)]
#[kube(status = "DpuServiceStatus")]
#[kube(schema = "disabled")]
pub struct DpuServiceSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "configPorts"
    )]
    pub config_ports: Option<DpuServiceConfigPorts>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deployInCluster"
    )]
    pub deploy_in_cluster: Option<bool>,
    #[serde(rename = "helmChart")]
    pub helm_chart: DpuServiceHelmChart,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interfaces: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paused: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceDaemonSet"
    )]
    pub service_daemon_set: Option<DpuServiceServiceDaemonSet>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "serviceID")]
    pub service_id: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigPorts {
    pub ports: Vec<DpuServiceConfigPortsPorts>,
    #[serde(rename = "serviceType")]
    pub service_type: DpuServiceConfigPortsServiceType,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigPortsPorts {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "nodePort")]
    pub node_port: Option<i64>,
    pub port: i64,
    pub protocol: DpuServiceConfigPortsPortsProtocol,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuServiceConfigPortsPortsProtocol {
    #[serde(rename = "TCP")]
    Tcp,
    #[serde(rename = "UDP")]
    Udp,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuServiceConfigPortsServiceType {
    NodePort,
    #[serde(rename = "ClusterIP")]
    ClusterIp,
    None,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceHelmChart {
    pub source: DpuServiceHelmChartSource,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<BTreeMap<String, serde_json::Value>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceHelmChartSource {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chart: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "releaseName"
    )]
    pub release_name: Option<String>,
    #[serde(rename = "repoURL")]
    pub repo_url: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceServiceDaemonSet {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeSelector"
    )]
    pub node_selector: Option<DpuServiceServiceDaemonSetNodeSelector>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<BTreeMap<String, IntOrString>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "updateStrategy"
    )]
    pub update_strategy: Option<DpuServiceServiceDaemonSetUpdateStrategy>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceServiceDaemonSetNodeSelector {
    #[serde(rename = "nodeSelectorTerms")]
    pub node_selector_terms: Vec<DpuServiceServiceDaemonSetNodeSelectorNodeSelectorTerms>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceServiceDaemonSetNodeSelectorNodeSelectorTerms {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions:
        Option<Vec<DpuServiceServiceDaemonSetNodeSelectorNodeSelectorTermsMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchFields"
    )]
    pub match_fields:
        Option<Vec<DpuServiceServiceDaemonSetNodeSelectorNodeSelectorTermsMatchFields>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceServiceDaemonSetNodeSelectorNodeSelectorTermsMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceServiceDaemonSetNodeSelectorNodeSelectorTermsMatchFields {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceServiceDaemonSetUpdateStrategy {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "rollingUpdate"
    )]
    pub rolling_update: Option<DpuServiceServiceDaemonSetUpdateStrategyRollingUpdate>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub r#type: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceServiceDaemonSetUpdateStrategyRollingUpdate {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "maxSurge")]
    pub max_surge: Option<IntOrString>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "maxUnavailable"
    )]
    pub max_unavailable: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "configPorts"
    )]
    pub config_ports: Option<BTreeMap<String, Vec<DpuServiceStatusConfigPorts>>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "serviceID")]
    pub service_id: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceStatusConfigPorts {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "nodePort")]
    pub node_port: Option<i64>,
    pub port: i64,
    pub protocol: DpuServiceStatusConfigPortsProtocol,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuServiceStatusConfigPortsProtocol {
    #[serde(rename = "TCP")]
    Tcp,
    #[serde(rename = "UDP")]
    Udp,
}
