// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuservicecredentialrequests.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUServiceCredentialRequest",
    plural = "dpuservicecredentialrequests"
)]
#[kube(namespaced)]
#[kube(status = "DpuServiceCredentialRequestStatus")]
#[kube(schema = "disabled")]
pub struct DpuServiceCredentialRequestSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<DpuServiceCredentialRequestMetadata>,
    pub secret: DpuServiceCredentialRequestSecret,
    #[serde(rename = "serviceAccount")]
    pub service_account: DpuServiceCredentialRequestServiceAccount,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "targetCluster"
    )]
    pub target_cluster: Option<DpuServiceCredentialRequestTargetCluster>,
    #[serde(rename = "type")]
    pub r#type: DpuServiceCredentialRequestType,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceCredentialRequestMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceCredentialRequestSecret {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceCredentialRequestServiceAccount {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceCredentialRequestTargetCluster {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuServiceCredentialRequestType {
    #[serde(rename = "kubeconfig")]
    Kubeconfig,
    #[serde(rename = "tokenFile")]
    TokenFile,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceCredentialRequestStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "expirationTimestamp"
    )]
    pub expiration_timestamp: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "issuedAt")]
    pub issued_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceAccount"
    )]
    pub service_account: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "targetCluster"
    )]
    pub target_cluster: Option<String>,
}
