// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuserviceconfigurations.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUServiceConfiguration",
    plural = "dpuserviceconfigurations"
)]
#[kube(namespaced)]
#[kube(schema = "disabled")]
pub struct DpuServiceConfigurationSpec {
    #[serde(rename = "deploymentServiceName")]
    pub deployment_service_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interfaces: Option<Vec<DpuServiceConfigurationInterfaces>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceConfiguration"
    )]
    pub service_configuration: Option<DpuServiceConfigurationServiceConfiguration>,
    #[serde(rename = "upgradePolicy")]
    pub upgrade_policy: DpuServiceConfigurationUpgradePolicy,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigurationInterfaces {
    pub name: String,
    pub network: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetwork"
    )]
    pub virtual_network: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigurationServiceConfiguration {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "configPorts"
    )]
    pub config_ports: Option<DpuServiceConfigurationServiceConfigurationConfigPorts>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deployInCluster"
    )]
    pub deploy_in_cluster: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "helmChart")]
    pub helm_chart: Option<DpuServiceConfigurationServiceConfigurationHelmChart>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceDaemonSet"
    )]
    pub service_daemon_set: Option<DpuServiceConfigurationServiceConfigurationServiceDaemonSet>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigurationServiceConfigurationConfigPorts {
    pub ports: Vec<DpuServiceConfigurationServiceConfigurationConfigPortsPorts>,
    #[serde(rename = "serviceType")]
    pub service_type: DpuServiceConfigurationServiceConfigurationConfigPortsServiceType,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigurationServiceConfigurationConfigPortsPorts {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "nodePort")]
    pub node_port: Option<i64>,
    pub port: i64,
    pub protocol: DpuServiceConfigurationServiceConfigurationConfigPortsPortsProtocol,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuServiceConfigurationServiceConfigurationConfigPortsPortsProtocol {
    #[serde(rename = "TCP")]
    Tcp,
    #[serde(rename = "UDP")]
    Udp,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuServiceConfigurationServiceConfigurationConfigPortsServiceType {
    NodePort,
    #[serde(rename = "ClusterIP")]
    ClusterIp,
    None,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigurationServiceConfigurationHelmChart {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<BTreeMap<String, serde_json::Value>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigurationServiceConfigurationServiceDaemonSet {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<BTreeMap<String, IntOrString>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "updateStrategy"
    )]
    pub update_strategy:
        Option<DpuServiceConfigurationServiceConfigurationServiceDaemonSetUpdateStrategy>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigurationServiceConfigurationServiceDaemonSetUpdateStrategy {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "rollingUpdate"
    )]
    pub rolling_update: Option<
        DpuServiceConfigurationServiceConfigurationServiceDaemonSetUpdateStrategyRollingUpdate,
    >,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub r#type: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigurationServiceConfigurationServiceDaemonSetUpdateStrategyRollingUpdate {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "maxSurge")]
    pub max_surge: Option<IntOrString>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "maxUnavailable"
    )]
    pub max_unavailable: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigurationUpgradePolicy {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "applyNodeEffect"
    )]
    pub apply_node_effect: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceConfigurationStatus {}
