// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpustoragepolicies.storage.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "storage.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUStoragePolicy",
    plural = "dpustoragepolicies"
)]
#[kube(namespaced)]
#[kube(status = "DpuStoragePolicyStatus")]
#[kube(schema = "disabled")]
pub struct DpuStoragePolicySpec {
    #[serde(rename = "dpuStorageVendors")]
    pub dpu_storage_vendors: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<BTreeMap<String, String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "selectionAlgorithm"
    )]
    pub selection_algorithm: Option<DpuStoragePolicySelectionAlgorithm>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuStoragePolicySelectionAlgorithm {
    Random,
    NumberVolumes,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuStoragePolicyStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
