// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuvpcs.vpc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "vpc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUVPC",
    plural = "dpuvpcs"
)]
#[kube(namespaced)]
#[kube(status = "DpuvpcStatus")]
#[kube(schema = "disabled")]
pub struct DpuvpcSpec {
    #[serde(rename = "interNetworkAccess")]
    pub inter_network_access: bool,
    #[serde(rename = "isolationClassName")]
    pub isolation_class_name: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeSelector"
    )]
    pub node_selector: Option<DpuvpcNodeSelector>,
    pub tenant: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuvpcNodeSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<DpuvpcNodeSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuvpcNodeSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuvpcStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetworks"
    )]
    pub virtual_networks: Option<Vec<DpuvpcStatusVirtualNetworks>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuvpcStatusVirtualNetworks {
    pub name: String,
}
