// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuvolumeattachments.storage.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "storage.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUVolumeAttachment",
    plural = "dpuvolumeattachments"
)]
#[kube(namespaced)]
#[kube(status = "DpuVolumeAttachmentStatus")]
#[kube(schema = "disabled")]
pub struct DpuVolumeAttachmentSpec {
    #[serde(rename = "dpuNodeName")]
    pub dpu_node_name: String,
    #[serde(rename = "dpuVolumeName")]
    pub dpu_volume_name: String,
    #[serde(rename = "functionType")]
    pub function_type: DpuVolumeAttachmentFunctionType,
    #[serde(rename = "hotplugFunction")]
    pub hotplug_function: bool,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuVolumeAttachmentFunctionType {
    #[serde(rename = "pf")]
    Pf,
    #[serde(rename = "vf")]
    Vf,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVolumeAttachmentStatus {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "attachmentMetadata"
    )]
    pub attachment_metadata: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "controllerAttached"
    )]
    pub controller_attached: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dpu: Option<DpuVolumeAttachmentStatusDpu>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuAttached"
    )]
    pub dpu_attached: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVolumeAttachmentStatusDpu {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "deviceName"
    )]
    pub device_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "nvmeAttrs")]
    pub nvme_attrs: Option<DpuVolumeAttachmentStatusDpuNvmeAttrs>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "pciAddress"
    )]
    pub pci_address: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtioFSAttrs"
    )]
    pub virtio_fs_attrs: Option<DpuVolumeAttachmentStatusDpuVirtioFsAttrs>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVolumeAttachmentStatusDpuNvmeAttrs {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "namespaceID"
    )]
    pub namespace_id: Option<i64>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "namespaceUUID"
    )]
    pub namespace_uuid: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVolumeAttachmentStatusDpuVirtioFsAttrs {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "filesystemTag"
    )]
    pub filesystem_tag: Option<String>,
}
