// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_isolationclasses.vpc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "vpc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "IsolationClass",
    plural = "isolationclasses"
)]
#[kube(schema = "disabled")]
pub struct IsolationClassSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<BTreeMap<String, String>>,
    pub provisioner: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct IsolationClassStatus {}
