// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_serviceinterfaces.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "ServiceInterface",
    plural = "serviceinterfaces"
)]
#[kube(namespaced)]
#[kube(status = "ServiceInterfaceStatus")]
#[kube(schema = "disabled")]
pub struct ServiceInterfaceSpec {
    #[serde(rename = "interfaceType")]
    pub interface_type: ServiceInterfaceInterfaceType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ovn: Option<ServiceInterfaceOvn>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pf: Option<ServiceInterfacePf>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub physical: Option<ServiceInterfacePhysical>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service: Option<ServiceInterfaceService>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vf: Option<ServiceInterfaceVf>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vlan: Option<ServiceInterfaceVlan>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ServiceInterfaceInterfaceType {
    #[serde(rename = "vlan")]
    Vlan,
    #[serde(rename = "physical")]
    Physical,
    #[serde(rename = "pf")]
    Pf,
    #[serde(rename = "vf")]
    Vf,
    #[serde(rename = "ovn")]
    Ovn,
    #[serde(rename = "service")]
    Service,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceOvn {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "externalBridge"
    )]
    pub external_bridge: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfacePf {
    #[serde(rename = "pfID")]
    pub pf_id: i64,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetwork"
    )]
    pub virtual_network: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfacePhysical {
    #[serde(rename = "interfaceName")]
    pub interface_name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceService {
    #[serde(rename = "interfaceName")]
    pub interface_name: String,
    pub network: String,
    #[serde(rename = "serviceID")]
    pub service_id: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetwork"
    )]
    pub virtual_network: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceVf {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "parentInterfaceRef"
    )]
    pub parent_interface_ref: Option<String>,
    #[serde(rename = "pfID")]
    pub pf_id: i64,
    #[serde(rename = "vfID")]
    pub vf_id: i64,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetwork"
    )]
    pub virtual_network: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceVlan {
    #[serde(rename = "parentInterfaceRef")]
    pub parent_interface_ref: String,
    #[serde(rename = "vlanID")]
    pub vlan_id: i64,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
