// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_servicechainsets.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "ServiceChainSet",
    plural = "servicechainsets"
)]
#[kube(namespaced)]
#[kube(status = "ServiceChainSetStatus")]
#[kube(schema = "disabled")]
pub struct ServiceChainSetSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeSelector"
    )]
    pub node_selector: Option<ServiceChainSetNodeSelector>,
    pub template: ServiceChainSetTemplate,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSetNodeSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<ServiceChainSetNodeSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSetNodeSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSetTemplate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ServiceChainSetTemplateMetadata>,
    pub spec: ServiceChainSetTemplateSpec,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSetTemplateMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSetTemplateSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    pub switches: Vec<ServiceChainSetTemplateSpecSwitches>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSetTemplateSpecSwitches {
    pub ports: Vec<ServiceChainSetTemplateSpecSwitchesPorts>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceMTU"
    )]
    pub service_mtu: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSetTemplateSpecSwitchesPorts {
    #[serde(rename = "serviceInterface")]
    pub service_interface: ServiceChainSetTemplateSpecSwitchesPortsServiceInterface,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSetTemplateSpecSwitchesPortsServiceInterface {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ipam: Option<ServiceChainSetTemplateSpecSwitchesPortsServiceInterfaceIpam>,
    #[serde(rename = "matchLabels")]
    pub match_labels: BTreeMap<String, String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSetTemplateSpecSwitchesPortsServiceInterfaceIpam {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "defaultGateway"
    )]
    pub default_gateway: Option<bool>,
    #[serde(rename = "matchLabels")]
    pub match_labels: BTreeMap<String, String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "setDefaultRoute"
    )]
    pub set_default_route: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSetStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "numberApplied"
    )]
    pub number_applied: Option<i32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "numberReady"
    )]
    pub number_ready: Option<i32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
