// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_serviceinterfacesets.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "ServiceInterfaceSet",
    plural = "serviceinterfacesets"
)]
#[kube(namespaced)]
#[kube(status = "ServiceInterfaceSetStatus")]
#[kube(schema = "disabled")]
pub struct ServiceInterfaceSetSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeSelector"
    )]
    pub node_selector: Option<ServiceInterfaceSetNodeSelector>,
    pub template: ServiceInterfaceSetTemplate,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetNodeSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<ServiceInterfaceSetNodeSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetNodeSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetTemplate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ServiceInterfaceSetTemplateMetadata>,
    pub spec: ServiceInterfaceSetTemplateSpec,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetTemplateMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetTemplateSpec {
    #[serde(rename = "interfaceType")]
    pub interface_type: ServiceInterfaceSetTemplateSpecInterfaceType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ovn: Option<ServiceInterfaceSetTemplateSpecOvn>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pf: Option<ServiceInterfaceSetTemplateSpecPf>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub physical: Option<ServiceInterfaceSetTemplateSpecPhysical>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service: Option<ServiceInterfaceSetTemplateSpecService>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vf: Option<ServiceInterfaceSetTemplateSpecVf>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vlan: Option<ServiceInterfaceSetTemplateSpecVlan>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum ServiceInterfaceSetTemplateSpecInterfaceType {
    #[serde(rename = "vlan")]
    Vlan,
    #[serde(rename = "physical")]
    Physical,
    #[serde(rename = "pf")]
    Pf,
    #[serde(rename = "vf")]
    Vf,
    #[serde(rename = "ovn")]
    Ovn,
    #[serde(rename = "service")]
    Service,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetTemplateSpecOvn {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "externalBridge"
    )]
    pub external_bridge: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetTemplateSpecPf {
    #[serde(rename = "pfID")]
    pub pf_id: i64,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetwork"
    )]
    pub virtual_network: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetTemplateSpecPhysical {
    #[serde(rename = "interfaceName")]
    pub interface_name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetTemplateSpecService {
    #[serde(rename = "interfaceName")]
    pub interface_name: String,
    pub network: String,
    #[serde(rename = "serviceID")]
    pub service_id: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetwork"
    )]
    pub virtual_network: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetTemplateSpecVf {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "parentInterfaceRef"
    )]
    pub parent_interface_ref: Option<String>,
    #[serde(rename = "pfID")]
    pub pf_id: i64,
    #[serde(rename = "vfID")]
    pub vf_id: i64,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetwork"
    )]
    pub virtual_network: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetTemplateSpecVlan {
    #[serde(rename = "parentInterfaceRef")]
    pub parent_interface_ref: String,
    #[serde(rename = "vlanID")]
    pub vlan_id: i64,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceInterfaceSetStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "numberApplied"
    )]
    pub number_applied: Option<i32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "numberReady"
    )]
    pub number_ready: Option<i32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
