// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuclusters.provisioning.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "provisioning.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUCluster",
    plural = "dpuclusters"
)]
#[kube(namespaced)]
#[kube(status = "DpuClusterStatus")]
#[kube(schema = "disabled")]
pub struct DpuClusterSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "clusterEndpoint"
    )]
    pub cluster_endpoint: Option<DpuClusterClusterEndpoint>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kubeconfig: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "maxNodes")]
    pub max_nodes: Option<i64>,
    #[serde(rename = "type")]
    pub r#type: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuClusterClusterEndpoint {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keepalived: Option<DpuClusterClusterEndpointKeepalived>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuClusterClusterEndpointKeepalived {
    pub interface: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeSelector"
    )]
    pub node_selector: Option<BTreeMap<String, String>>,
    pub vip: String,
    #[serde(rename = "virtualRouterID")]
    pub virtual_router_id: i64,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuClusterStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    pub phase: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}
