// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpudeployments.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUDeployment",
    plural = "dpudeployments"
)]
#[kube(namespaced)]
#[kube(status = "DpuDeploymentStatus")]
#[kube(schema = "disabled")]
pub struct DpuDeploymentSpec {
    pub dpus: DpuDeploymentDpus,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "revisionHistoryLimit"
    )]
    pub revision_history_limit: Option<i32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceChains"
    )]
    pub service_chains: Option<DpuDeploymentServiceChains>,
    pub services: BTreeMap<String, DpuDeploymentServices>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentDpus {
    pub bfb: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "dpuSets")]
    pub dpu_sets: Option<Vec<DpuDeploymentDpusDpuSets>>,
    pub flavor: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeEffect"
    )]
    pub node_effect: Option<DpuDeploymentDpusNodeEffect>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentDpusDpuSets {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuAnnotations"
    )]
    pub dpu_annotations: Option<BTreeMap<String, String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuSelector"
    )]
    pub dpu_selector: Option<BTreeMap<String, String>>,
    #[serde(rename = "nameSuffix")]
    pub name_suffix: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeSelector"
    )]
    pub node_selector: Option<DpuDeploymentDpusDpuSetsNodeSelector>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentDpusDpuSetsNodeSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<DpuDeploymentDpusDpuSetsNodeSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentDpusDpuSetsNodeSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentDpusNodeEffect {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "customAction"
    )]
    pub custom_action: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "customLabel"
    )]
    pub custom_label: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub drain: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hold: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "noEffect")]
    pub no_effect: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub taint: Option<DpuDeploymentDpusNodeEffectTaint>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentDpusNodeEffectTaint {
    pub effect: String,
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "timeAdded")]
    pub time_added: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentServiceChains {
    pub switches: Vec<DpuDeploymentServiceChainsSwitches>,
    #[serde(rename = "upgradePolicy")]
    pub upgrade_policy: DpuDeploymentServiceChainsUpgradePolicy,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentServiceChainsSwitches {
    pub ports: Vec<DpuDeploymentServiceChainsSwitchesPorts>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceMTU"
    )]
    pub service_mtu: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentServiceChainsSwitchesPorts {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service: Option<DpuDeploymentServiceChainsSwitchesPortsService>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceInterface"
    )]
    pub service_interface: Option<DpuDeploymentServiceChainsSwitchesPortsServiceInterface>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentServiceChainsSwitchesPortsService {
    pub interface: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ipam: Option<DpuDeploymentServiceChainsSwitchesPortsServiceIpam>,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentServiceChainsSwitchesPortsServiceIpam {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "defaultGateway"
    )]
    pub default_gateway: Option<bool>,
    #[serde(rename = "matchLabels")]
    pub match_labels: BTreeMap<String, String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "setDefaultRoute"
    )]
    pub set_default_route: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentServiceChainsSwitchesPortsServiceInterface {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ipam: Option<DpuDeploymentServiceChainsSwitchesPortsServiceInterfaceIpam>,
    #[serde(rename = "matchLabels")]
    pub match_labels: BTreeMap<String, String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentServiceChainsSwitchesPortsServiceInterfaceIpam {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "defaultGateway"
    )]
    pub default_gateway: Option<bool>,
    #[serde(rename = "matchLabels")]
    pub match_labels: BTreeMap<String, String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "setDefaultRoute"
    )]
    pub set_default_route: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentServiceChainsUpgradePolicy {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "applyNodeEffect"
    )]
    pub apply_node_effect: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentServices {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "dependsOn")]
    pub depends_on: Option<Vec<DpuDeploymentServicesDependsOn>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceConfiguration"
    )]
    pub service_configuration: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceTemplate"
    )]
    pub service_template: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentServicesDependsOn {
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeploymentStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
