// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuservicenads.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUServiceNAD",
    plural = "dpuservicenads"
)]
#[kube(namespaced)]
#[kube(status = "DpuServiceNadStatus")]
#[kube(schema = "disabled")]
pub struct DpuServiceNadSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bridge: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "chainedCNIs"
    )]
    pub chained_cn_is: Option<Vec<DpuServiceNadChainedCnIs>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ipam: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<DpuServiceNadMetadata>,
    #[serde(rename = "resourceType")]
    pub resource_type: DpuServiceNadResourceType,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceMTU"
    )]
    pub service_mtu: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceNadChainedCnIs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<BTreeMap<String, serde_json::Value>>,
    #[serde(rename = "type")]
    pub r#type: DpuServiceNadChainedCnIsType,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuServiceNadChainedCnIsType {
    #[serde(rename = "rdma")]
    Rdma,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceNadMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuServiceNadResourceType {
    #[serde(rename = "vf")]
    Vf,
    #[serde(rename = "sf")]
    Sf,
    #[serde(rename = "veth")]
    Veth,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceNadStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
}
