// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuservicetemplates.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUServiceTemplate",
    plural = "dpuservicetemplates"
)]
#[kube(namespaced)]
#[kube(status = "DpuServiceTemplateStatus")]
#[kube(schema = "disabled")]
pub struct DpuServiceTemplateSpec {
    #[serde(rename = "deploymentServiceName")]
    pub deployment_service_name: String,
    #[serde(rename = "helmChart")]
    pub helm_chart: DpuServiceTemplateHelmChart,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "resourceRequirements"
    )]
    pub resource_requirements: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceTemplateHelmChart {
    pub source: DpuServiceTemplateHelmChartSource,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<BTreeMap<String, serde_json::Value>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceTemplateHelmChartSource {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chart: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "releaseName"
    )]
    pub release_name: Option<String>,
    #[serde(rename = "repoURL")]
    pub repo_url: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceTemplateStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub versions: Option<BTreeMap<String, String>>,
}
