// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuserviceipams.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUServiceIPAM",
    plural = "dpuserviceipams"
)]
#[kube(namespaced)]
#[kube(status = "DpuServiceIpamStatus")]
#[kube(schema = "disabled")]
pub struct DpuServiceIpamSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "clusterSelector"
    )]
    pub cluster_selector: Option<DpuServiceIpamClusterSelector>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "ipv4Network"
    )]
    pub ipv4_network: Option<DpuServiceIpamIpv4Network>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "ipv4Subnet"
    )]
    pub ipv4_subnet: Option<DpuServiceIpamIpv4Subnet>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<DpuServiceIpamMetadata>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeSelector"
    )]
    pub node_selector: Option<DpuServiceIpamNodeSelector>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamClusterSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<DpuServiceIpamClusterSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamClusterSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamIpv4Network {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allocations: Option<BTreeMap<String, String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "defaultGateway"
    )]
    pub default_gateway: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclusions: Option<Vec<String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "gatewayIndex"
    )]
    pub gateway_index: Option<i32>,
    pub network: String,
    #[serde(rename = "prefixSize")]
    pub prefix_size: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<DpuServiceIpamIpv4NetworkRoutes>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamIpv4NetworkRoutes {
    pub dst: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamIpv4Subnet {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "defaultGateway"
    )]
    pub default_gateway: Option<bool>,
    pub gateway: String,
    #[serde(rename = "perNodeIPCount")]
    pub per_node_ip_count: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<DpuServiceIpamIpv4SubnetRoutes>>,
    pub subnet: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamIpv4SubnetRoutes {
    pub dst: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamNodeSelector {
    #[serde(rename = "nodeSelectorTerms")]
    pub node_selector_terms: Vec<DpuServiceIpamNodeSelectorNodeSelectorTerms>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamNodeSelectorNodeSelectorTerms {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<DpuServiceIpamNodeSelectorNodeSelectorTermsMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchFields"
    )]
    pub match_fields: Option<Vec<DpuServiceIpamNodeSelectorNodeSelectorTermsMatchFields>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamNodeSelectorNodeSelectorTermsMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamNodeSelectorNodeSelectorTermsMatchFields {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceIpamStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
