// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpustoragevendors.storage.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "storage.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUStorageVendor",
    plural = "dpustoragevendors"
)]
#[kube(namespaced)]
#[kube(status = "DpuStorageVendorStatus")]
#[kube(schema = "disabled")]
pub struct DpuStorageVendorSpec {
    #[serde(rename = "pluginName")]
    pub plugin_name: String,
    #[serde(rename = "storageClassName")]
    pub storage_class_name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuStorageVendorStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuClusters"
    )]
    pub dpu_clusters: Option<Vec<DpuStorageVendorStatusDpuClusters>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuStorageVendorStatusDpuClusters {
    pub name: String,
    pub namespace: String,
}
