// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuserviceinterfaces.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUServiceInterface",
    plural = "dpuserviceinterfaces"
)]
#[kube(namespaced)]
#[kube(status = "DpuServiceInterfaceStatus")]
#[kube(schema = "disabled")]
pub struct DpuServiceInterfaceSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "clusterSelector"
    )]
    pub cluster_selector: Option<DpuServiceInterfaceClusterSelector>,
    pub template: DpuServiceInterfaceTemplate,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceClusterSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<DpuServiceInterfaceClusterSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceClusterSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<DpuServiceInterfaceTemplateMetadata>,
    pub spec: DpuServiceInterfaceTemplateSpec,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeSelector"
    )]
    pub node_selector: Option<DpuServiceInterfaceTemplateSpecNodeSelector>,
    pub template: DpuServiceInterfaceTemplateSpecTemplate,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecNodeSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<DpuServiceInterfaceTemplateSpecNodeSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecNodeSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecTemplate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<DpuServiceInterfaceTemplateSpecTemplateMetadata>,
    pub spec: DpuServiceInterfaceTemplateSpecTemplateSpec,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecTemplateMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecTemplateSpec {
    #[serde(rename = "interfaceType")]
    pub interface_type: DpuServiceInterfaceTemplateSpecTemplateSpecInterfaceType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ovn: Option<DpuServiceInterfaceTemplateSpecTemplateSpecOvn>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pf: Option<DpuServiceInterfaceTemplateSpecTemplateSpecPf>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub physical: Option<DpuServiceInterfaceTemplateSpecTemplateSpecPhysical>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service: Option<DpuServiceInterfaceTemplateSpecTemplateSpecService>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vf: Option<DpuServiceInterfaceTemplateSpecTemplateSpecVf>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vlan: Option<DpuServiceInterfaceTemplateSpecTemplateSpecVlan>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuServiceInterfaceTemplateSpecTemplateSpecInterfaceType {
    #[serde(rename = "vlan")]
    Vlan,
    #[serde(rename = "physical")]
    Physical,
    #[serde(rename = "pf")]
    Pf,
    #[serde(rename = "vf")]
    Vf,
    #[serde(rename = "ovn")]
    Ovn,
    #[serde(rename = "service")]
    Service,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecTemplateSpecOvn {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "externalBridge"
    )]
    pub external_bridge: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecTemplateSpecPf {
    #[serde(rename = "pfID")]
    pub pf_id: i64,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetwork"
    )]
    pub virtual_network: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecTemplateSpecPhysical {
    #[serde(rename = "interfaceName")]
    pub interface_name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecTemplateSpecService {
    #[serde(rename = "interfaceName")]
    pub interface_name: String,
    pub network: String,
    #[serde(rename = "serviceID")]
    pub service_id: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetwork"
    )]
    pub virtual_network: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecTemplateSpecVf {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "parentInterfaceRef"
    )]
    pub parent_interface_ref: Option<String>,
    #[serde(rename = "pfID")]
    pub pf_id: i64,
    #[serde(rename = "vfID")]
    pub vf_id: i64,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "virtualNetwork"
    )]
    pub virtual_network: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceTemplateSpecTemplateSpecVlan {
    #[serde(rename = "parentInterfaceRef")]
    pub parent_interface_ref: String,
    #[serde(rename = "vlanID")]
    pub vlan_id: i64,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceInterfaceStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
