// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuservicechains.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUServiceChain",
    plural = "dpuservicechains"
)]
#[kube(namespaced)]
#[kube(status = "DpuServiceChainStatus")]
#[kube(schema = "disabled")]
pub struct DpuServiceChainSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "clusterSelector"
    )]
    pub cluster_selector: Option<DpuServiceChainClusterSelector>,
    pub template: DpuServiceChainTemplate,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainClusterSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<DpuServiceChainClusterSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainClusterSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<DpuServiceChainTemplateMetadata>,
    pub spec: DpuServiceChainTemplateSpec,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeSelector"
    )]
    pub node_selector: Option<DpuServiceChainTemplateSpecNodeSelector>,
    pub template: DpuServiceChainTemplateSpecTemplate,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateSpecNodeSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<DpuServiceChainTemplateSpecNodeSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateSpecNodeSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateSpecTemplate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<DpuServiceChainTemplateSpecTemplateMetadata>,
    pub spec: DpuServiceChainTemplateSpecTemplateSpec,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateSpecTemplateMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateSpecTemplateSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    pub switches: Vec<DpuServiceChainTemplateSpecTemplateSpecSwitches>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateSpecTemplateSpecSwitches {
    pub ports: Vec<DpuServiceChainTemplateSpecTemplateSpecSwitchesPorts>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceMTU"
    )]
    pub service_mtu: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateSpecTemplateSpecSwitchesPorts {
    #[serde(rename = "serviceInterface")]
    pub service_interface: DpuServiceChainTemplateSpecTemplateSpecSwitchesPortsServiceInterface,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateSpecTemplateSpecSwitchesPortsServiceInterface {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ipam: Option<DpuServiceChainTemplateSpecTemplateSpecSwitchesPortsServiceInterfaceIpam>,
    #[serde(rename = "matchLabels")]
    pub match_labels: BTreeMap<String, String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainTemplateSpecTemplateSpecSwitchesPortsServiceInterfaceIpam {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "defaultGateway"
    )]
    pub default_gateway: Option<bool>,
    #[serde(rename = "matchLabels")]
    pub match_labels: BTreeMap<String, String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "setDefaultRoute"
    )]
    pub set_default_route: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuServiceChainStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
