// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuvolumes.storage.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "storage.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUVolume",
    plural = "dpuvolumes"
)]
#[kube(namespaced)]
#[kube(status = "DpuVolumeStatus")]
#[kube(schema = "disabled")]
pub struct DpuVolumeSpec {
    #[serde(rename = "accessModes")]
    pub access_modes: Vec<String>,
    #[serde(rename = "dpuStoragePolicyName")]
    pub dpu_storage_policy_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<BTreeMap<String, String>>,
    pub resources: DpuVolumeResources,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "volumeMode"
    )]
    pub volume_mode: Option<DpuVolumeVolumeMode>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVolumeResources {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<BTreeMap<String, IntOrString>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuVolumeVolumeMode {
    Filesystem,
    Block,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVolumeStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phase: Option<DpuVolumeStatusPhase>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<DpuVolumeStatusState>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuVolumeStatusPhase {
    Pending,
    Bound,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVolumeStatusState {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "csiDriverName"
    )]
    pub csi_driver_name: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuCluster"
    )]
    pub dpu_cluster: Option<DpuVolumeStatusStateDpuCluster>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<BTreeMap<String, String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "persistentVolumeClaimRef"
    )]
    pub persistent_volume_claim_ref: Option<DpuVolumeStatusStatePersistentVolumeClaimRef>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "selectedDPUStorageVendorName"
    )]
    pub selected_dpu_storage_vendor_name: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "storageClassName"
    )]
    pub storage_class_name: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "storageVendorPluginName"
    )]
    pub storage_vendor_plugin_name: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "volumeInfo"
    )]
    pub volume_info: Option<DpuVolumeStatusStateVolumeInfo>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVolumeStatusStateDpuCluster {
    pub name: String,
    pub namespace: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVolumeStatusStatePersistentVolumeClaimRef {
    pub name: String,
    pub namespace: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVolumeStatusStateVolumeInfo {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "accessModes"
    )]
    pub access_modes: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capacity: Option<BTreeMap<String, IntOrString>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "volumeAttributes"
    )]
    pub volume_attributes: Option<BTreeMap<String, String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "volumeMode"
    )]
    pub volume_mode: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "volumeName"
    )]
    pub volume_name: Option<String>,
}
