// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_dpuvirtualnetworks.vpc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "vpc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUVirtualNetwork",
    plural = "dpuvirtualnetworks"
)]
#[kube(namespaced)]
#[kube(status = "DpuVirtualNetworkStatus")]
#[kube(schema = "disabled")]
pub struct DpuVirtualNetworkSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "bridgedNetwork"
    )]
    pub bridged_network: Option<DpuVirtualNetworkBridgedNetwork>,
    #[serde(rename = "externallyRouted")]
    pub externally_routed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub masquerade: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeSelector"
    )]
    pub node_selector: Option<DpuVirtualNetworkNodeSelector>,
    #[serde(rename = "type")]
    pub r#type: DpuVirtualNetworkType,
    #[serde(rename = "vpcName")]
    pub vpc_name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVirtualNetworkBridgedNetwork {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ipam: Option<DpuVirtualNetworkBridgedNetworkIpam>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVirtualNetworkBridgedNetworkIpam {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ipv4: Option<DpuVirtualNetworkBridgedNetworkIpamIpv4>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVirtualNetworkBridgedNetworkIpamIpv4 {
    pub dhcp: bool,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "excludeIPs"
    )]
    pub exclude_i_ps: Option<Vec<DpuVirtualNetworkBridgedNetworkIpamIpv4ExcludeIPs>>,
    pub subnet: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVirtualNetworkBridgedNetworkIpamIpv4ExcludeIPs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<DpuVirtualNetworkBridgedNetworkIpamIpv4ExcludeIPsRange>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVirtualNetworkBridgedNetworkIpamIpv4ExcludeIPsRange {
    pub end: String,
    pub start: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVirtualNetworkNodeSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<DpuVirtualNetworkNodeSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVirtualNetworkNodeSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuVirtualNetworkType {
    Bridged,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuVirtualNetworkStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
