// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /projects/carbide/crates/dpf-beta/doca-platform/deploy/charts/dpf-operator/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_servicechains.svc.dpu.nvidia.com.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "svc.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "ServiceChain",
    plural = "servicechains"
)]
#[kube(namespaced)]
#[kube(status = "ServiceChainStatus")]
#[kube(schema = "disabled")]
pub struct ServiceChainSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    pub switches: Vec<ServiceChainSwitches>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSwitches {
    pub ports: Vec<ServiceChainSwitchesPorts>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serviceMTU"
    )]
    pub service_mtu: Option<i64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSwitchesPorts {
    #[serde(rename = "serviceInterface")]
    pub service_interface: ServiceChainSwitchesPortsServiceInterface,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSwitchesPortsServiceInterface {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ipam: Option<ServiceChainSwitchesPortsServiceInterfaceIpam>,
    #[serde(rename = "matchLabels")]
    pub match_labels: BTreeMap<String, String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainSwitchesPortsServiceInterfaceIpam {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "defaultGateway"
    )]
    pub default_gateway: Option<bool>,
    #[serde(rename = "matchLabels")]
    pub match_labels: BTreeMap<String, String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "setDefaultRoute"
    )]
    pub set_default_route: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ServiceChainStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
